package typescript

import (
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/loy-go/loy/internal/filesystem"
	"github.com/loy-go/loy/internal/generator/naming"
	"github.com/loy-go/loy/internal/route"
)

var (
	pathParamRegex      = regexp.MustCompile(`(?::([a-zA-Z0-9_]+)|\{([a-zA-Z0-9_]+)\})`)
	versionSegmentRegex = regexp.MustCompile(`^v[0-9]+$`)
)

// GenerateResult contains the generated TypeScript artifacts.
type GenerateResult struct {
	TypesPath    string
	TypesSource  string
	ClientPath   string
	ClientSource string
}

// GenerateOptions configures the TypeScript generation pipeline.
type GenerateOptions struct {
	RootDir string
	OutDir  string
}

// Generate produces types.ts and client.ts from Go DTOs and routes.
func Generate(fs filesystem.FileSystem, opts GenerateOptions) (*GenerateResult, error) {
	if opts.RootDir == "" {
		opts.RootDir = "."
	}
	if opts.OutDir == "" {
		opts.OutDir = "client"
	}

	types, err := ParseDTOs(fs, opts.RootDir)
	if err != nil {
		return nil, fmt.Errorf("parsing Go DTOs: %w", err)
	}

	routes, err := route.InspectRoutes(fs, opts.RootDir)
	if err != nil {
		return nil, fmt.Errorf("inspecting routes: %w", err)
	}

	typesSource := GenerateTypes(types)
	clientSource := GenerateClient(routes, types)

	// Path sandbox validation: ensure OutDir is within RootDir
	targetOut := opts.OutDir
	if !filepath.IsAbs(targetOut) {
		targetOut = filepath.Clean(filepath.Join(opts.RootDir, targetOut))
		rel, err := filepath.Rel(opts.RootDir, targetOut)
		if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
			return nil, fmt.Errorf("invalid output directory %q: escapes root directory %q", opts.OutDir, opts.RootDir)
		}
	} else {
		if _, err := filesystem.CleanAndValidatePath(opts.RootDir, targetOut); err != nil {
			return nil, fmt.Errorf("invalid output directory %q: %w", opts.OutDir, err)
		}
	}

	typesPath := filepath.Join(targetOut, "types.ts")
	clientPath := filepath.Join(targetOut, "client.ts")

	if err := fs.MkdirAll(targetOut, 0755); err != nil {
		return nil, fmt.Errorf("creating output directory %s: %w", targetOut, err)
	}

	if err := fs.WriteFile(typesPath, []byte(typesSource), 0644); err != nil {
		return nil, fmt.Errorf("writing %s: %w", typesPath, err)
	}

	if err := fs.WriteFile(clientPath, []byte(clientSource), 0644); err != nil {
		return nil, fmt.Errorf("writing %s: %w", clientPath, err)
	}

	return &GenerateResult{
		TypesPath:    typesPath,
		TypesSource:  typesSource,
		ClientPath:   clientPath,
		ClientSource: clientSource,
	}, nil
}

// GenerateTypes renders TypeScript interfaces for all discovered DTOs.
func GenerateTypes(types []TypeDefinition) string {
	var sb strings.Builder
	sb.WriteString("// Code generated by Loy. DO NOT EDIT.\n\n")

	if len(types) == 0 {
		sb.WriteString("// No Go DTO structs discovered.\nexport {};\n")
		return sb.String()
	}

	// Sort types alphabetically for deterministic output
	sort.Slice(types, func(i, j int) bool {
		return types[i].Name < types[j].Name
	})

	for _, t := range types {
		fmt.Fprintf(&sb, "export interface %s {\n", t.Name)
		for _, f := range t.Fields {
			optMarker := ""
			typeStr := f.Type
			if f.Optional && f.Nullable {
				optMarker = "?"
				typeStr += " | null"
			} else if f.Optional {
				optMarker = "?"
			} else if f.Nullable {
				typeStr += " | null"
			}
			fmt.Fprintf(&sb, "  %s%s: %s;\n", f.Name, optMarker, typeStr)
		}
		sb.WriteString("}\n\n")
	}

	return sb.String()
}

// GenerateClient renders a typed fetch API client for discovered routes and DTOs.
func GenerateClient(routes []route.RouteInfo, types []TypeDefinition) string {
	typeMap := make(map[string]bool)
	for _, t := range types {
		typeMap[t.Name] = true
	}

	usedTypes := make(map[string]bool)

	type clientMethod struct {
		name       string
		method     string
		pathExpr   string
		params     []string
		bodyType   string
		returnType string
		hasBody    bool
		isList     bool
	}

	seenNames := make(map[string]int)
	var methods []clientMethod

	for _, r := range routes {
		method := strings.ToUpper(r.Method)
		if method == "ALL" || method == "USE" {
			continue
		}

		params, pathExpr := extractPathParams(r.Path)
		resourceName, isList, action := inferResourceAndAction(r.Path, method, len(params) > 0)
		pascalResource := toPascalCase(resourceName)

		reqType := "any"
		resType := "any"

		candidateReq := pascalResource + "Request"
		candidateRes := pascalResource + "Resource"

		if typeMap[candidateReq] {
			reqType = candidateReq
			usedTypes[candidateReq] = true
		}
		if typeMap[candidateRes] {
			resType = candidateRes
			usedTypes[candidateRes] = true
		}

		methodName := buildMethodName(action, pascalResource, resourceName, params)
		if count := seenNames[methodName]; count > 0 {
			seenNames[methodName]++
			methodName = fmt.Sprintf("%s%d", methodName, count+1)
		} else {
			seenNames[methodName] = 1
		}

		hasBody := method == "POST" || method == "PUT" || method == "PATCH"
		ret := resType
		if isList && resType != "any" {
			ret = resType + "[]"
		} else if method == "DELETE" {
			ret = "void"
		}

		methods = append(methods, clientMethod{
			name:       methodName,
			method:     method,
			pathExpr:   pathExpr,
			params:     params,
			bodyType:   reqType,
			returnType: ret,
			hasBody:    hasBody,
			isList:     isList,
		})
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by Loy. DO NOT EDIT.\n\n")

	// Imports from types.ts
	if len(usedTypes) > 0 {
		var imported []string
		for t := range usedTypes {
			imported = append(imported, t)
		}
		sort.Strings(imported)
		fmt.Fprintf(&sb, "import type { %s } from './types';\n\n", strings.Join(imported, ", "))
	}

	// ClientConfig interface
	sb.WriteString(`export interface ClientConfig {
  baseURL?: string;
  fetch?: typeof fetch;
  headers?: Record<string, string>;
}

export class LoyClient {
  private baseURL: string;
  private fetch: typeof fetch;
  private headers: Record<string, string>;

  constructor(config: ClientConfig = {}) {
    this.baseURL = (config.baseURL || '').replace(/\/$/, '');
    this.fetch = config.fetch || (typeof globalThis !== 'undefined' ? globalThis.fetch.bind(globalThis) : undefined as any);
    this.headers = config.headers || {};
  }

  private async request<T>(method: string, path: string, body?: any, query?: Record<string, any>): Promise<T> {
    let url = ` + "`${this.baseURL}${path}`" + `;
    if (query) {
      const searchParams = new URLSearchParams();
      for (const [k, v] of Object.entries(query)) {
        if (v !== undefined && v !== null) {
          searchParams.append(k, String(v));
        }
      }
      const q = searchParams.toString();
      if (q) url += ` + "`?${q}`" + `;
    }

    const res = await this.fetch(url, {
      method,
      headers: {
        'Content-Type': 'application/json',
        ...this.headers,
      },
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!res.ok) {
      const text = await res.text();
      throw new Error(` + "`HTTP ${res.status}: ${text}`" + `);
    }

    if (res.status === 204) {
      return undefined as unknown as T;
    }

    const contentType = res.headers.get('content-type') || '';
    if (contentType.includes('application/json')) {
      return res.json() as Promise<T>;
    }
    return undefined as unknown as T;
  }
`)

	for _, m := range methods {
		var args []string
		for _, p := range m.params {
			args = append(args, fmt.Sprintf("%s: string | number", p))
		}
		if m.hasBody {
			args = append(args, fmt.Sprintf("data: %s", m.bodyType))
		}
		if m.isList {
			args = append(args, "params?: { limit?: number; offset?: number; [key: string]: any }")
		}

		argsStr := strings.Join(args, ", ")
		bodyArg := "undefined"
		if m.hasBody {
			bodyArg = "data"
		}
		queryArg := "undefined"
		if m.isList {
			queryArg = "params"
		}

		fmt.Fprintf(&sb, "\n  async %s(%s): Promise<%s> {\n", m.name, argsStr, m.returnType)
		fmt.Fprintf(&sb, "    return this.request<%s>('%s', `%s`, %s, %s);\n", m.returnType, m.method, m.pathExpr, bodyArg, queryArg)
		sb.WriteString("  }\n")
	}

	sb.WriteString("}\n\n")
	sb.WriteString("export function createClient(config?: ClientConfig): LoyClient {\n  return new LoyClient(config);\n}\n")

	return sb.String()
}

func extractPathParams(path string) ([]string, string) {
	var params []string
	seen := make(map[string]bool)

	converted := pathParamRegex.ReplaceAllStringFunc(path, func(m string) string {
		pName := m
		if strings.HasPrefix(pName, ":") {
			pName = strings.TrimPrefix(pName, ":")
		} else if strings.HasPrefix(pName, "{") && strings.HasSuffix(pName, "}") {
			pName = strings.TrimSuffix(strings.TrimPrefix(pName, "{"), "}")
		}
		if !seen[pName] {
			seen[pName] = true
			params = append(params, pName)
		}
		return "${" + pName + "}"
	})

	return params, converted
}

func inferResourceAndAction(path string, method string, hasParams bool) (resource string, isList bool, action string) {
	clean := strings.Trim(path, "/")
	parts := strings.Split(clean, "/")

	var nonParamSegments []string
	for _, p := range parts {
		if !strings.HasPrefix(p, ":") && !strings.HasPrefix(p, "{") && p != "api" && !versionSegmentRegex.MatchString(p) {
			nonParamSegments = append(nonParamSegments, p)
		}
	}

	if len(nonParamSegments) == 0 {
		return "root", false, strings.ToLower(method)
	}

	resource = nonParamSegments[0]
	if len(nonParamSegments) > 1 {
		lastSeg := nonParamSegments[len(nonParamSegments)-1]
		if lastSeg != resource {
			action = lastSeg
		}
	}

	switch method {
	case "GET":
		if hasParams {
			action = "get"
			isList = false
		} else {
			action = "list"
			isList = true
		}
	case "POST":
		if action == "" {
			action = "create"
		}
	case "PUT":
		if action == "" {
			action = "update"
		}
	case "PATCH":
		if action == "" {
			action = "patch"
		}
	case "DELETE":
		if action == "" {
			action = "delete"
		}
	default:
		if action == "" {
			action = strings.ToLower(method)
		}
	}

	return resource, isList, action
}

func buildMethodName(action, pascalResource, resourceName string, params []string) string {
	if action == "list" {
		return "list" + toPascalCasePlural(resourceName)
	}
	if action == "get" {
		if len(params) > 0 {
			return "get" + pascalResource
		}
		return "get" + toPascalCase(resourceName)
	}
	if action == "create" {
		return "create" + pascalResource
	}
	if action == "update" {
		return "update" + pascalResource
	}
	if action == "patch" {
		return "patch" + pascalResource
	}
	if action == "delete" {
		return "delete" + pascalResource
	}
	return action + pascalResource
}

func toPascalCasePlural(s string) string {
	s = strings.TrimSpace(s)
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	var res strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			res.WriteString(strings.ToUpper(p[:1]) + strings.ToLower(p[1:]))
		}
	}
	return res.String()
}

func toPascalCase(s string) string {
	s = strings.TrimSpace(s)
	// Singularize plural for resource names using canonical pluralizer
	s = naming.Singularize(s)
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	var res strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			res.WriteString(strings.ToUpper(p[:1]) + strings.ToLower(p[1:]))
		}
	}
	return res.String()
}
