// Code generated by Loy; DO NOT EDIT.

package domain

import (
	"time"
)

// Notification represents the domain entity for notification.
type Notification struct {
	ID        int64     `json:"id" db:"id"`
	Channel   string    `json:"channel" db:"channel"`
	Recipient string    `json:"recipient" db:"recipient"`
	Body      string    `json:"body" db:"body"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// TableName returns the database table name for Notification.
func (Notification) TableName() string {
	return "notifications"
}
