// Code generated by Loy; DO NOT EDIT.

package domain

import (
	"context"
)

// Repository defines persistence operations for Notification.
type Repository interface {
	FindByID(ctx context.Context, id int64) (*Notification, error)
	FindAll(ctx context.Context, limit, offset int) ([]*Notification, error)
	Create(ctx context.Context, entity *Notification) error
	Update(ctx context.Context, entity *Notification) error
	Delete(ctx context.Context, id int64) error
}
