package rules

import (
	"context"
	"go/parser"
	"go/token"
	"strings"
	"testing"

	"github.com/loy-go/loy/internal/architecture"
	"github.com/loy-go/loy/internal/graph"
)

func TestComprehensiveRules(t *testing.T) {
	ctx := context.Background()

	t.Run("ARCH-003 domain to transport", func(t *testing.T) {
		g := graph.New()
		g.AddNode("app/domain/user", "Domain", nil)
		g.AddNode("app/transport/http", "Transport", nil)
		g.AddEdge("app/domain/user", "app/transport/http", "user.go", 12)

		analysis := &architecture.Analysis{Graph: g}
		r := &RuleArch003{}
		vs := r.Check(ctx, analysis)
		if len(vs) != 1 || vs[0].RuleID != "ARCH-003" {
			t.Fatalf("expected ARCH-003 violation, got: %+v", vs)
		}
	})

	t.Run("ARCH-004 application to transport", func(t *testing.T) {
		g := graph.New()
		g.AddNode("app/service/order", "Application", nil)
		g.AddNode("app/transport/http", "Transport", nil)
		g.AddEdge("app/service/order", "app/transport/http", "order.go", 14)

		analysis := &architecture.Analysis{Graph: g}
		r := &RuleArch004{}
		vs := r.Check(ctx, analysis)
		if len(vs) != 1 || vs[0].RuleID != "ARCH-004" {
			t.Fatalf("expected ARCH-004 violation, got: %+v", vs)
		}
	})

	t.Run("ARCH-005 application to concrete infra", func(t *testing.T) {
		g := graph.New()
		g.AddNode("app/service/order", "Application", nil)
		g.AddNode("app/repository/pg", "Infrastructure", nil)
		g.AddEdge("app/service/order", "app/repository/pg", "order.go", 16)

		analysis := &architecture.Analysis{Graph: g}
		r := &RuleArch005{}
		vs := r.Check(ctx, analysis)
		if len(vs) != 1 || vs[0].RuleID != "ARCH-005" {
			t.Fatalf("expected ARCH-005 violation, got: %+v", vs)
		}
	})

	t.Run("ARCH-006 infrastructure to transport", func(t *testing.T) {
		g := graph.New()
		g.AddNode("app/repository/pg", "Infrastructure", nil)
		g.AddNode("app/transport/http", "Transport", nil)
		g.AddEdge("app/repository/pg", "app/transport/http", "pg.go", 18)

		analysis := &architecture.Analysis{Graph: g}
		r := &RuleArch006{}
		vs := r.Check(ctx, analysis)
		if len(vs) != 1 || vs[0].RuleID != "ARCH-006" {
			t.Fatalf("expected ARCH-006 violation, got: %+v", vs)
		}
	})

	t.Run("ARCH-007 transport business logic persistence import", func(t *testing.T) {
		fset := token.NewFileSet()
		src := `package handler
import "database/sql"
type H struct { DB *sql.DB }
`
		f, _ := parser.ParseFile(fset, "handler.go", src, 0)
		analysis := &architecture.Analysis{
			Files: []*architecture.FileAST{
				{
					Path:    "internal/transport/http/handler.go",
					Layer:   architecture.LayerTransport,
					AST:     f,
					FileSet: fset,
				},
			},
		}

		r := &RuleArch007{}
		vs := r.Check(ctx, analysis)
		if len(vs) != 1 || vs[0].RuleID != "ARCH-007" {
			t.Fatalf("expected ARCH-007 violation, got: %+v", vs)
		}
	})

	t.Run("ARCH-009 forbidden web framework in application", func(t *testing.T) {
		fset := token.NewFileSet()
		src := `package service
import "github.com/gofiber/fiber"
type S struct { App *fiber.App }
`
		f, _ := parser.ParseFile(fset, "service.go", src, 0)
		analysis := &architecture.Analysis{
			Files: []*architecture.FileAST{
				{
					Path:    "internal/service/service.go",
					Layer:   architecture.LayerApplication,
					AST:     f,
					FileSet: fset,
				},
			},
		}

		r := &RuleArch009{}
		vs := r.Check(ctx, analysis)
		if len(vs) != 1 || vs[0].RuleID != "ARCH-009" {
			t.Fatalf("expected ARCH-009 violation, got: %+v", vs)
		}
	})

	t.Run("ARCH-010 layer direction violation", func(t *testing.T) {
		g := graph.New()
		g.AddNode("app/internal/domain/user", "Domain", nil)
		g.AddNode("app/internal/transport/http", "Transport", nil)
		g.AddEdge("app/internal/domain/user", "app/internal/transport/http", "user.go", 22)

		analysis := &architecture.Analysis{Graph: g}
		r := &RuleArch010{}
		vs := r.Check(ctx, analysis)
		if len(vs) != 1 || vs[0].RuleID != "ARCH-010" {
			t.Fatalf("expected ARCH-010 violation, got: %+v", vs)
		}
	})

	t.Run("ARCH-011 forbidden service locator", func(t *testing.T) {
		fset := token.NewFileSet()
		src := `package service
import "go.uber.org/dig"
func Setup() *dig.Container { return dig.New() }
`
		f, _ := parser.ParseFile(fset, "service.go", src, 0)
		analysis := &architecture.Analysis{
			Files: []*architecture.FileAST{
				{
					Path:    "internal/service/service.go",
					AST:     f,
					FileSet: fset,
				},
			},
		}

		r := &RuleArch011{}
		vs := r.Check(ctx, analysis)
		if len(vs) != 1 || vs[0].RuleID != "ARCH-011" {
			t.Fatalf("expected ARCH-011 violation, got: %+v", vs)
		}
	})

	t.Run("ARCH-014 unmanaged generated file location", func(t *testing.T) {
		fset := token.NewFileSet()
		src := `// Code generated by loy. DO NOT EDIT.
package domain
`
		f, _ := parser.ParseFile(fset, "domain/user.go", src, parser.ParseComments)
		analysis := &architecture.Analysis{
			Files: []*architecture.FileAST{
				{
					Path:     "domain/user.go",
					AST:      f,
					Comments: f.Comments,
				},
			},
		}

		r := &RuleArch014{}
		vs := r.Check(ctx, analysis)
		if len(vs) != 1 || vs[0].RuleID != "ARCH-014" {
			t.Fatalf("expected ARCH-014 violation, got: %+v", vs)
		}
	})

	t.Run("ARCH-014 corrupted comment region", func(t *testing.T) {
		src := `package service
// loy:region:handlers
func A() {}
// Unclosed region marker!
`
		analysis := &architecture.Analysis{
			Files: []*architecture.FileAST{
				{
					Path:    "internal/service/service.go",
					Content: []byte(src),
				},
			},
		}

		r := &RuleArch014{}
		vs := r.Check(ctx, analysis)
		if len(vs) != 1 || vs[0].RuleID != "ARCH-014" {
			t.Fatalf("expected ARCH-014 violation for unclosed region, got: %+v", vs)
		}
		if !strings.Contains(vs[0].Message, "unclosed region") {
			t.Errorf("expected unclosed region message, got: %s", vs[0].Message)
		}
	})
}
