package cli

import (
	"fmt"
	"path/filepath"

	"github.com/loy-go/loy/internal/filesystem"
	"github.com/loy-go/loy/internal/process"
	"github.com/spf13/cobra"
)

const preCommitScript = `#!/bin/sh
# loy:hook:pre-commit
# Automatically generated by Loy. Validates architectural layer invariants.
loy check --quiet || {
    echo "Architecture violations detected by loy check. Commit blocked."
    exit 1
}
`

const prePushScript = `#!/bin/sh
# loy:hook:pre-push
# Automatically generated by Loy. Validates tests before push to main/master.
while read local_ref local_oid remote_ref remote_oid
do
    case "$remote_ref" in
        refs/heads/main|refs/heads/master)
            echo "Running pre-push verification for $remote_ref..."
            go test -short ./... || {
                echo "Tests failed. Push to $remote_ref blocked."
                exit 1
            }
            ;;
    esac
done
exit 0
`

func newHookCmd(fs filesystem.FileSystem, runner process.Runner) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "hook",
		Short: "Manage Git lifecycle hooks for architecture enforcement",
		Long:  `loy hook installs and manages Git hooks (e.g. pre-commit and pre-push) to enforce clean architecture rules and testing locally.`,
	}

	installCmd := &cobra.Command{
		Use:   "install [path]",
		Short: "Install Git pre-commit and pre-push hooks to enforce checks and tests before push",
		RunE: func(cmd *cobra.Command, args []string) error {
			rootDir := "."
			if len(args) > 0 {
				rootDir = args[0]
			}

			gitDir := filepath.Join(rootDir, ".git")
			gitExists, err := fs.Exists(gitDir)
			if err != nil {
				return fmt.Errorf("checking git directory: %w", err)
			}
			if !gitExists {
				return fmt.Errorf("no .git directory found in %s (initialize git repository first)", rootDir)
			}

			hooksDir := filepath.Join(gitDir, "hooks")
			if err := fs.MkdirAll(hooksDir, 0755); err != nil {
				return fmt.Errorf("creating git hooks directory: %w", err)
			}

			hookPath := filepath.Join(hooksDir, "pre-commit")
			if err := fs.WriteFile(hookPath, []byte(preCommitScript), 0755); err != nil {
				return fmt.Errorf("writing pre-commit hook: %w", err)
			}

			pushHookPath := filepath.Join(hooksDir, "pre-push")
			if err := fs.WriteFile(pushHookPath, []byte(prePushScript), 0755); err != nil {
				return fmt.Errorf("writing pre-push hook: %w", err)
			}

			cliOpts := GetOptions(cmd.Context())
			if !cliOpts.Quiet {
				_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Installed Loy Git hooks (pre-commit, pre-push) in %s\n", hooksDir)
			}
			return nil
		},
	}

	cmd.AddCommand(installCmd)
	return cmd
}
