// Code generated by Loy; DO NOT EDIT.

package domain

import (
	"time"
)

// Organization represents the domain entity for organization.
type Organization struct {
	ID        int64     `json:"id" db:"id"`
	Name      string    `json:"name" db:"name"`
	Plan      string    `json:"plan" db:"plan"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// TableName returns the database table name for Organization.
func (Organization) TableName() string {
	return "organizations"
}
