// Code generated by Loy; DO NOT EDIT.

package domain

import (
	"context"
)

// Repository defines persistence operations for Organization.
type Repository interface {
	FindByID(ctx context.Context, id int64) (*Organization, error)
	FindAll(ctx context.Context, limit, offset int) ([]*Organization, error)
	Create(ctx context.Context, entity *Organization) error
	Update(ctx context.Context, entity *Organization) error
	Delete(ctx context.Context, id int64) error
}
