package model

import "io/fs"

// Artifact represents a single file or managed section produced by a Generator.
type Artifact struct {
	// Path is the relative path from project/target root.
	Path string

	// Content is the rendered raw content of the artifact.
	Content []byte

	// Ownership defines how collisions and overwrites are handled.
	Ownership Ownership

	// Permissions is the file mode (e.g. 0644 or 0755).
	Permissions fs.FileMode

	// Region is optional; set if this artifact represents a splice into a MixedOwned file.
	Region string
}

// GeneratedFileHeader is the standard header placed on GeneratedOwned Go files.
const GeneratedFileHeader = "// Code generated by Loy; DO NOT EDIT."
