// Code generated by Loy; DO NOT EDIT.

package domain

import (
	"context"
)

// Repository defines persistence operations for User.
type Repository interface {
	FindByID(ctx context.Context, id int64) (*User, error)
	FindAll(ctx context.Context, limit, offset int) ([]*User, error)
	Create(ctx context.Context, entity *User) error
	Update(ctx context.Context, entity *User) error
	Delete(ctx context.Context, id int64) error
}
