// Code generated by Loy; DO NOT EDIT.

package domain

import (
	"time"
)

// User represents the domain entity for user.
type User struct {
	ID        int64     `json:"id" db:"id"`
	Name      string    `json:"name" db:"name"`
	Email     string    `json:"email" db:"email"`
	Role      string    `json:"role" db:"role"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// TableName returns the database table name for User.
func (User) TableName() string {
	return "users"
}
