// Code generated by Loy; DO NOT EDIT.

package domain

import (
	"time"
)

// Billing represents the domain entity for billing.
type Billing struct {
	ID        int64     `json:"id" db:"id"`
	Amount    float64   `json:"amount" db:"amount"`
	Status    string    `json:"status" db:"status"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// TableName returns the database table name for Billing.
func (Billing) TableName() string {
	return "billings"
}
