// Code generated by Loy; DO NOT EDIT.

package domain

import (
	"context"
)

// Repository defines persistence operations for Billing.
type Repository interface {
	FindByID(ctx context.Context, id int64) (*Billing, error)
	FindAll(ctx context.Context, limit, offset int) ([]*Billing, error)
	Create(ctx context.Context, entity *Billing) error
	Update(ctx context.Context, entity *Billing) error
	Delete(ctx context.Context, id int64) error
}
